---
title: "Scoring with RF"
author: "Faith Platz"
date: "11/23/2019"
output: pdf_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(randomForest)
```


```{r, message=FALSE}
load("scoring_cleaned.RData")
load("RF.RData")

# need to add in the missing value flags that were not created with scoring data
tour.score <- tour.score %>% 
  mutate(Book_Months_num.NA = as.factor(0),
         Optionals_Bin.NA = as.factor(0),
         TourWeek.NA = as.factor(0),
         Tour_Region.binned.NA = as.factor(0))


# use alternative cutoff to classify Book_12Mo
RF.prob <- predict(RF, newdata=tour.score, type="prob")[,2]
RF.class <- as.factor(ifelse(RF.prob >= RFThresh$threshold, 1,0))
tour.score["pred.Book_12Mo"] <- data.frame(RF.class)

# add the EvalID back in
tour.score.results <- read_csv("scoring_data.csv") %>% 
  dplyr::select(EvalID) %>% 
  bind_cols(tour.score) %>%
  dplyr::select(EvalID, pred.Book_12Mo) %>% 
  mutate_all(as.factor)

# write to a csv (commented out after running)
# write_csv(tour.score.results, "tour.score.results.update.csv")
```


```{r}
# check against Irina's
load("ip.rf.model.score.RData")
irina0 <- RF.class.score.dat %>%
  as.data.frame()

names(irina0) <- "pred.Book_12Mo"

irina <- read_csv("scoring_data.csv") %>% 
  dplyr::select(EvalID) %>% 
  bind_cols(irina0) %>%
  dplyr::select(EvalID, pred.Book_12Mo) %>% 
  mutate_all(as.factor)

tour.score.results %>% 
  anti_join(irina) # 359 mismatches


# Check against Alex's
load("alex_RF_results.RData")
alex0 <- tour.score %>%
  dplyr::select(RF.class) %>% 
  rename("pred.Book_12Mo" = "RF.class")

alex <- read_csv("scoring_data.csv") %>% 
  dplyr::select(EvalID) %>% 
  bind_cols(alex0) %>%
  dplyr::select(EvalID, pred.Book_12Mo) %>% 
  mutate_all(as.factor)

tour.score.results %>% 
  anti_join(alex) # 533 mismatches

# check against James'
james0 <- read_csv("James.score.csv") %>% 
  rename("pred.Book_12Mo" = "x") %>% 
  dplyr::select(pred.Book_12Mo)

james <- read_csv("scoring_data.csv") %>% 
  dplyr::select(EvalID) %>% 
  bind_cols(james0) %>%
  dplyr::select(EvalID, pred.Book_12Mo) %>% 
  mutate_all(as.factor)

tour.score.results %>% 
  anti_join(james) # 359 mismatches
```


